# TEMPLATE: Kubernetes kubeconfig placeholder for an org
# The orchestrator will generate a real kubeconfig via talosctl and write to ~/.guildnet/state/kube/<org>.config.
# This file is a placeholder to help users know where things go.
#
# A real kubeconfig will look like:
# apiVersion: v1
# kind: Config
# clusters:
# - name: acme
#   cluster:
#     certificate-authority-data: <base64>
#     server: https://10.0.0.10:6443
# contexts:
# - name: acme
#   context:
#     cluster: acme
#     user: acme
# current-context: acme
# users:
# - name: acme
#   user:
#     client-certificate-data: <base64>
#     client-key-data: <base64>
