version: "3.8"
services:
  orchestrator:
    image: mvp-orchestrator:${IMAGE_TAG:-latest}
    build:
      context: ..
      dockerfile: docker/orchestrator.Dockerfile
    container_name: mvp-orchestrator
    environment:
      - ORCHESTRATOR_TOKEN=${ORCHESTRATOR_TOKEN}
      - DASHBOARD_TOKEN=${DASHBOARD_TOKEN}
      - ORCHESTRATOR_CONFIG=/app/configs/orchestrator.example.yaml
      - K3D_API_HOST=host.docker.internal
      - WORKSPACE_DIR=/workspace
    volumes:
      - ../orchestrator/configs:/app/configs:ro
      - ../state:/state
      - ../scripts:/scripts:ro
      - ../:/workspace:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "0.0.0.0:18080:8080"
    networks:
      - mvp

  dashboard:
    image: node:20-alpine
    working_dir: /app
    command: ["sh", "-lc", "npm ci && npx tsx server/server.ts"]
    environment:
      - DASHBOARD_TOKEN=${DASHBOARD_TOKEN}
      - ORCHESTRATOR_URL=http://mvp-orchestrator:8080
      - ORCHESTRATOR_TOKEN=${ORCHESTRATOR_TOKEN}
      - UI_DEV=0
      - LOCAL_ENSURE=0
    volumes:
      - ../dashboard:/app
      - ../scripts:/scripts:ro
      - ../state:/state
    ports:
      - "127.0.0.1:8090:8090"
    networks:
      - mvp

networks:
  mvp:
    driver: bridge
