name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend deps
        run: |
          cd backend
          npm i --no-audit --no-fund
      - name: Lint
        run: |
          cd backend
          npm run lint
      - name: Test
        run: |
          cd backend
          npm test
      - name: Docker build (smoke)
        run: |
          docker build -t orchestrator-backend:ci ./backend
