apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mvp-agents
resources:
  - ../base/namespace.yaml
  - crd-agenttask.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - operator-deployment.yaml
